version: "3"
services:
  hub: 
    image: selenium/hub
## May be commented to run with grid
    ports: 
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    shm_size: '2gb'
    depends_on:
      - hub
    environment: 
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
## Volume mapping for file DOWNLOADS
    volumes:
      - .\target\downloads:/home/seluser/Downloads
  firefox:
    image: selenium/node-firefox
    shm_size: '2gb'
    depends_on:
      - hub
    environment: 
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
## Volume mapping for file DOWNLOADS
    volumes:
      - .\target\downloads:/home/seluser/Downloads

  allure:
    image: "frankescobar/allure-docker-service"
    depends_on:
      - chrome
      - firefox
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
      KEEP_HISTORY: 1
#   ports:
#     - "5050:5050"
    volumes:
      - .\target\allure-results:/app/allure-results
      - .\target\allure-reports:/app/default-reports

### Adding FIRST SUITE run
  regression-firefox:
    image: serge11elzar/maven_docker
    depends_on:
      - chrome
      - firefox
    environment:
      - browser=firefox
      - HUB_HOST=hub
      - SUITE=general_suite.xml
    volumes:
      - .\target\allure-results:/usr/share/maven_docker/target/allure-results
### Adding ANOTHER SUITE run
  first-suite-chrome:
    image: serge11elzar/maven_docker
    depends_on:
      - chrome
      - firefox
    environment:
      - browser=chrome
      - HUB_HOST=hub
      - SUITE=first_suite.xml
    volumes:
      - .\target\allure-results:/usr/share/maven_docker/target/allure-results
      - .\target\first-suite-results:/usr/share/maven_docker/test-output
### Adding ANOTHER SUITE run
  second-suite-firefox:
    image: serge11elzar/maven_docker
    depends_on:
      - chrome
      - firefox
    environment:
      - browser=firefox
      - HUB_HOST=hub
      - SUITE=second_suite.xml
    volumes:
      - .\target\allure-results:/usr/share/maven_docker/target/allure-results
      - .\target\second-suite-results:/usr/share/maven_docker/test-output
