version: "3"
services:
  hub: 
    image: selenium/hub
    ports: 
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome
    shm_size: '2gb'
    depends_on:
      - hub
    environment: 
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  firefox:
    image: selenium/node-firefox
    shm_size: '2gb'
    depends_on:
      - hub
    environment: 
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
# Starting already created docker image when running tests
  regression-firefox:
    image: serge11elzar/maven_docker
    depends_on:
      - chrome
      - firefox
    environment:
      - browser=firefox
      - HUB_HOST=hub
      - SUITE=general_suite.xml
    volumes:
      - .\target\allure-results:/usr/share/maven_docker/target/allure-results
# Adding parameters for ANOTHER SUITE run
  first-suite-chrome:
    image: serge11elzar/maven_docker
    depends_on:
      - chrome
      - firefox
    environment:
      - browser=chrome
      - HUB_HOST=hub
      - SUITE=general_suite.xml
    volumes:
      - .\target\first-suite-results:/usr/share/maven_docker/test-output
# Adding parameters for ANOTHER SUITE run
  second-suite-firefox:
    image: serge11elzar/maven_docker
    depends_on:
      - chrome
      - firefox
    environment:
      - browser=firefox
      - HUB_HOST=hub
      - SUITE=second_suite.xml
    volumes:
      - .\target\second-suite-results:/usr/share/maven_docker/test-output
